include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - test/**
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/**/*.hive.dart
  plugins:
    - dart_code_metrics

linter:
  rules:
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_types_as_parameter_names
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - no_duplicate_case_values
    - prefer_void_to_null
    - unrelated_type_equality_checks
    - valid_regexps

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
  metrics-exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/**/*.hive.dart
  rules:
    - avoid-redundant-async
    - avoid-passing-async-when-sync-expected
    - avoid-redundant-async
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - avoid-nested-conditional-expressions
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - prefer-match-file-name